# Generated by Django 4.2.3 on 2024-02-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_customuser_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='pic',
        ),
    ]
