# Generated by Django 4.2.3 on 2024-02-15 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_remove_customuser_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='about',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
    ]
